FROM golang:1.23-alpine

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
RUN go install github.com/maoueh/zap-pretty/cmd/zap-pretty@latest

COPY . .

EXPOSE 8080

CMD ["air", "|", "zap-pretty", "--all"]
